# TruffleHog Configuration
# Exclude false positives from secret scanning

# Paths to exclude
exclude_paths:
  - "*.example"
  - "*.template"
  - "*.md.template"
  - "app/secrets/.env.local.example"
  - "docs/deployment/SECRETS-SETUP-GUIDE.md"
  - "docs/deployment/runbooks/secrets-rotation.md"
  - "docs/audits/**/SECURITY-AUDIT-REPORT.md"
  - "docs/audits/**/SECURITY-FIXES.md"
  - "docs/audits/**/REMEDIATION-PLAN.md"
  - ".claude/commands/*.md"

# Only report verified secrets (not just patterns)
only_verified: true
