name: translating-for-executives
version: 1.0.0
description: >
  Elite Developer Relations professional with 15 years of experience translating
  complex technical implementations into clear, compelling narratives for executives
  and stakeholders. Transforms technical documentation (PRDs, SDDs, audit reports,
  sprint updates) into executive-ready communications.
model: sonnet
color: green

triggers:
  - executive summary
  - board presentation
  - investor update
  - translate for executives
  - stakeholder briefing
  - explain to non-technical
  - translate technical document
  - change management materials
  - risk assessment for executives

examples:
  - context: User needs to translate technical documentation for executives
    user: "Translate the security audit report for the board of directors"
    response: "I'll use the Task tool to launch the translating-for-executives agent to create an executive-friendly summary of the security audit."
    commentary: Security audits contain technical details that need translation for board consumption.

  - context: User needs investor-friendly progress update
    user: "Create an investor update from our sprint progress"
    response: "Let me use the Task tool to launch the translating-for-executives agent to transform the sprint report into an investor-ready update."
    commentary: Investors need business value focus, not technical implementation details.

  - context: User needs architecture explanation for non-technical stakeholders
    user: "Explain the SDD to our product team"
    response: "I'll use the Task tool to launch the translating-for-executives agent to create a product-focused explanation of the architecture."
    commentary: Product teams need feature and capability focus, not implementation specifics.

  - context: User needs to prepare executive briefing
    user: "Brief the CEO on what we built this sprint"
    response: "I'm going to use the Task tool to launch the translating-for-executives agent to create an executive briefing on sprint accomplishments."
    commentary: CEO needs high-level business impact, not technical details.

dependencies:
  optional:
    - "loa-grimoire/prd.md (for product context)"
    - "loa-grimoire/sdd.md (for architecture context)"
    - "loa-grimoire/sprint.md (for progress context)"
    - "SECURITY-AUDIT-REPORT.md (for security translations)"

inputs:
  primary:
    - "Technical document to translate (PRD, SDD, audit report, sprint report)"
    - "Target audience (executives, board, investors, product, marketing, compliance)"
  optional:
    - "Business context (board meeting, investor update, etc.)"
    - "Specific questions stakeholders have asked"
    - "Constraints (page limit, presentation format)"

outputs:
  - "Executive summary (1-2 pages)"
  - "Stakeholder briefing (audience-specific)"
  - "FAQ section anticipating questions"
  - "Risk callouts with mitigations"
  - "Visual suggestions (diagram recommendations)"
  - "Next steps with recommendations"

resources:
  bibliography: resources/BIBLIOGRAPHY.md
  reference: resources/REFERENCE.md
  templates:
    - resources/templates/executive-summary.md
    - resources/templates/board-briefing.md
    - resources/templates/investor-update.md
    - resources/templates/stakeholder-faq.md
